services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql-springboot
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: springdb
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer:latest
    platform: linux/amd64
    container_name: adminer
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8080"  # Map host port 8081 to container port 8080
    networks:
      - spring-network

volumes:
  mysql_data:

networks:
  spring-network:
    driver: bridge